name: Main Workflow

on:
  workflow_dispatch:

jobs:
  call-shared-workflow:
    uses: cobbg/workflow-test-2/.github/workflows/variable.yaml@main
    with:
      some-input: 'testing123'

  print-result:
    needs: [call-shared-workflow]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: testing-artifact
          path: string
      - name: Output string
        run: echo string
