name: Main Workflow

on:
  workflow_dispatch:

jobs:
  call-shared-workflow:
    uses: cobbg/workflow-test-2/.github/workflows/variable.yml@main
    with:
      some-input: 'testing123'

  print-result:
    needs: [call-shared-workflow]
    runs-on: ubuntu-latest
    steps:
      - name: Print result from shared workflow
        #run: echo "The result is: ${{ needs.call-shared-workflow.outputs.result }}"
        run: echo "This is done"
