name: Main Workflow

on:
  push:
    branches:
      - main
      - testing
  workflow_dispatch:

jobs:
  testing:
    uses: cobbg/workflow-test-2/.github/workflows/variable.yaml@main
    with:
      some-input: 'testing123'
    run: |
      echo "This is a test"
