name: Inline Go Example

on:
  workflow_dispatch:

jobs:
  run-go-inline:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run inline Go code
        run: |
          cat <<'EOF' > main.go
          package main

          import (
            "fmt"
            "time"
          )

          func main() {
            fmt.Println("Hello from Go inside GitHub Actions!")
            fmt.Println("The time is:", time.Now())
          }
          EOF
          go run main.go
