name: Show Secret

on:
  push:
    branches:
      - main

jobs:
  reveal-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Output Repo
        run: |
          echo "Name of this repository: ${{ github.repository }}."

      - name: Output token
        run: |
          echo "This is the current token: ${{ secrets.GITHUB_TOKEN }}."
