name: Show Secret

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      manual_run:
        description: "Is this a manual run?"
        required: true
        type: choice
        options:
        - true
        - false

jobs:
  reveal-secret:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout repository
      #  uses: actions/checkout@v4

      - name: Output Repo
        run: |
          echo "Name of this repository: ${{ github.repository }}."

      - name: Output token
        run: |
          echo "This is the current token: ${{ secrets.GITHUB_TOKEN }}."

      - name: Get workflows
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows" | \
            jq -r '.workflows[] | select(.name == "Show Secret") | .id'

      - name: Output input
        run: |
          echo ${{ github.event.inputs.manual_run }}

      - name: Test if manually run
        if: ${{ github.event.inputs.manual_run == 'true' }}
        run: echo "Manually run"
