name: Show Secret

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:
    inputs:
      manual_run:
        description: "Is this a manual run?"
        required: true
        type: choice
        options:
        - true
        - false
      boolean_test:
        description: "Boolean test"
        required: true
        type: boolean
        default: false

jobs:
  reveal-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Set env variable
        run: |
          echo "TESTING=this_is_a_test_1.0" >> "GITHUB_ENV"
      - name: Echo env variable
        run: |
          echo ${TESTING}

