name: Test env var

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  reveal-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Set env variable
        run: |
          echo "TESTING=this_is_a_test_1.0" >> "GITHUB_ENV"
      - name: Echo env variable
        run: |
          echo "Env variable $TESTING"
          echo "Trying again $(TESTING)"
          echo "GitHub env variable ${{ env.TESTING }}"
          echo "TESTING=$TESTING"
          echo "123 $TESTING"

