name: Update file in workflow-test-2

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'File to update in target repo'
        required: true
        default: 'test.txt'

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo (workflow-test)
      uses: actions/checkout@v4

    - name: Checkout target repo (workflow-test-2)
      uses: actions/checkout@v4
      with:
        repository: cobbg/workflow-test-2
        token: ${{ secrets.TARGET_REPO_TOKEN }}
        path: target-repo

    - name: Make change in target repo
      run: |
        cd target-repo

        # Example change: append a timestamp to the file
        echo "Updated by workflow at $(date)" >> ${{ github.event.inputs.filename }}

        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add ${{ github.event.inputs.filename }}
        git commit -m "Automated update to ${{ github.event.inputs.filename }} from workflow-test"
        git push

